# Generated by Django 5.1.2 on 2024-12-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/books'),
        ),
        migrations.AlterField(
            model_name='books',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/books'),
        ),
    ]
