# Generated by Django 5.1.2 on 2024-12-06 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_book_image_alter_books_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Books', 'verbose_name_plural': 'Books'},
        ),
    ]
