# Generated by Django 5.1.2 on 2024-11-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Published Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/blogs', verbose_name='Image')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('content', models.TextField(verbose_name='Content')),
            ],
        ),
    ]
