# Generated by Django 5.1.1 on 2024-10-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeblog',
            name='slug',
            field=models.SlugField(max_length=80),
        ),
    ]
