# Generated by Django 5.1.1 on 2024-10-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homeblog_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeblog',
            old_name='title',
            new_name='category',
        ),
    ]
