# Generated by Django 5.1.2 on 2024-11-27 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeblog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='home.category', verbose_name='Category'),
        ),
    ]
