# Generated by Django 5.1.2 on 2024-12-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homeblog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeblog',
            name='blog_name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
