# Generated by Django 5.1.2 on 2024-12-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homeblog_blog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeblog',
            name='blog_name',
            field=models.CharField(blank=True, default='Default Blog Name', max_length=100, unique=True),
        ),
    ]
