# Generated by Django 5.1.2 on 2024-12-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homeblog_blog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeblog',
            name='blog_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
